// <auto-generated />
using System;
using EmployeeSalaryCalculation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeSalaryCalculation.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231126224650_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EmployeeSalaryCalculation.Data.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsBonusAdded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportingPersonId")
                        .HasColumnType("int");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.Property<double>("SalaryWithBonus")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1748),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2017, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yehfes ",
                            Position = "General Manager",
                            ReportingPersonId = 0,
                            Salary = 50000.900000000001,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1749)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1754),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2017, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ron",
                            Position = "Manager",
                            ReportingPersonId = 1,
                            Salary = 40000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1755)
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1759),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2018, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jaky",
                            Position = "Manager",
                            ReportingPersonId = 1,
                            Salary = 40000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1760)
                        },
                        new
                        {
                            Id = 4,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1764),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jack",
                            Position = "Office Executive",
                            ReportingPersonId = 2,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1765)
                        },
                        new
                        {
                            Id = 5,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1769),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2017, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jane",
                            Position = "Office Executive",
                            ReportingPersonId = 3,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1770)
                        },
                        new
                        {
                            Id = 6,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1773),
                            IsBonusAdded = false,
                            JoinDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hun",
                            Position = "Office Executive",
                            ReportingPersonId = 2,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1774)
                        },
                        new
                        {
                            Id = 7,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1778),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amber",
                            Position = "Office Executive",
                            ReportingPersonId = 3,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1779)
                        },
                        new
                        {
                            Id = 8,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1782),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nick",
                            Position = "Office Executive",
                            ReportingPersonId = 2,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1783)
                        },
                        new
                        {
                            Id = 9,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1787),
                            IsBonusAdded = false,
                            JoinDate = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laila",
                            Position = "Office Executive",
                            ReportingPersonId = 2,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1788)
                        },
                        new
                        {
                            Id = 10,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1792),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adam",
                            Position = "Office Executive",
                            ReportingPersonId = 3,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1793)
                        },
                        new
                        {
                            Id = 11,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1797),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2019, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Joss",
                            Position = "Office Executive",
                            ReportingPersonId = 3,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1798)
                        },
                        new
                        {
                            Id = 12,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1801),
                            IsBonusAdded = false,
                            JoinDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nissan",
                            Position = "Office Executive",
                            ReportingPersonId = 2,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1802)
                        },
                        new
                        {
                            Id = 13,
                            CreateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1806),
                            IsBonusAdded = true,
                            JoinDate = new DateTime(2019, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Adriano",
                            Position = "Office Executive",
                            ReportingPersonId = 2,
                            Salary = 20000.5,
                            SalaryWithBonus = 0.0,
                            UpdateDate = new DateTime(2023, 11, 27, 4, 46, 50, 45, DateTimeKind.Local).AddTicks(1806)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
